### PR TITLE
[DB-11205] Improved export schema output regarding applying assessment recommendations. 

### PR DESCRIPTION
**Pull request by makalaaneesh**
- Irrespective of whether we actually changed the schema (to add `WITH COLOCATION false` , we print a msg indicating that we have applied the assessment recommendations 
- Make the last msg be `Exported schema files created under directory: ...` 

Sample outputs

(non-empty sharded tables)
```
exporting the schema           done
Modified CREATE TABLE statements in "schema/tables/table.sql" according to the colocation and sharding recommendations of the assessment report.
The original DDLs have been preserved in "schema/tables/table.sql.orig" for reference.
Applied assessment recommendations.

Exported schema files created under directory: /Users/amakala/Documents/test/assessment/schema
```

(all colocated tables; no change to schema required)
```
exporting the schema           done
Applied assessment recommendations.

Exported schema files created under directory: /Users/amakala/Documents/test/assessment/schema
```

### CODE REVIEW

**Comment by sanyamsinghal** [comment]
@makalaaneesh, Have we removed this line now:
```
Modified CREATE TABLE statements in "schema/tables/table.sql" according to the colocation and sharding recommendations of the assessment report.
The original DDLs have been preserved in "schema/tables/table.sql.orig" for reference
```

**Comment by makalaaneesh** [comment]
> @makalaaneesh, Have we removed this line now:
> 
> ```
> Modified CREATE TABLE statements in "schema/tables/table.sql" according to the colocation and sharding recommendations of the assessment report.
> The original DDLs have been preserved in "schema/tables/table.sql.orig" for reference
> ```

@sanyamsinghal no no! 
Those two outputs are are just different cases of when the schema was modified. (one where there were some sharded tables, so modficiations were done, and one where all tables were colocated, and so no schema modifications were done.

**Comment by sanyamsinghal** [comment]
> > @makalaaneesh, Have we removed this line now:
> > ```
> > Modified CREATE TABLE statements in "schema/tables/table.sql" according to the colocation and sharding recommendations of the assessment report.
> > The original DDLs have been preserved in "schema/tables/table.sql.orig" for reference
> > ```
> 
> @sanyamsinghal no no! Those two outputs are are just different cases of when the schema was modified. (one where there were some sharded tables, so modficiations were done, and one where all tables were colocated, and so no schema modifications were done.

oh ok got it. Missed that part.
Just thinking if we should print `Applied Assessment Recommendations` in case of Colocated or not, since there are no actual changes done in that case.

**Comment by makalaaneesh** [comment]
> Just thinking if we should print `Applied Assessment Recommendations` in case of Colocated or not, since there are no actual changes done in that case.

I think this was @shubham-yb 's point to begin with. He had a case where all tables were colocated, and did not see any output, so he was confused as to whether the recommendations from assessment were applied or not. 

So we thought: irrespective of whether we are making modifications to the schema or not, we should inform the user that we have taken the assessment recommendations into consideration.

**Review by sanyamsinghal — APPROVED** [review]

**Pull request merged**
