### PR TITLE
Bug #685: Remove failed.sql file from previous runs of import schema command

### PR DESCRIPTION
**Pull request by sanyamsinghal**

### CODE REVIEW

**Review by priyanshi-yb — APPROVED** [review]
LGTM

**Review by rahulb-yb — COMMENTED** [review]
What would happen if nothing failed in the very first pass 🙂

**Comment by sanyamsinghal** [comment]
> What would happen if nothing failed in the very first pass 🙂

yeah thanks @rahulb-yb i missed that, didn't know that `os.Remove` will error out, thought it will be like `rm -rf` command

**Review by rahulb-yb — APPROVED** [review]
LGTM

**Pull request merged**
